name: Java CI/CD PipelLine

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Increment patch version
      run: |
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        PATCH=$(echo $CURRENT_VERSION | awk -F. '{print $3}')
        NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v P=$PATCH '{print $1"."$2"."P+1}')
        mvn versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false
        echo "Updated version to $NEW_VERSION"

    - name: Commit and Push updated version
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add pom.xml
        git commit -m "Update version to $NEW_VERSION"
        git push origin master

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-java-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/simple-java-app:latest
